FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

# Copy all the files
COPY . .

# Build the Next.js app
RUN npm run build

FROM node:18-alpine AS production

WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/next.config.ts ./next.config.ts
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "start"]
